name: "bj514's blog"
description: "bj514的博客"
navigation:
  - name: 首页
    url: /
  - name: 关于
    url: /about
  - name: 归档
    url: /archive
  - name: 标签
    url: /tags

# Pagination
paginate: 8

excerpt_separator: <!-- more -->

# Includes an icon in the footer for each username you enter
footer-links:
  behance:
  dribbble:
  email: huangyuhxp11@163.com
  facebook:
  flickr:
  github: aprogrammonkey 
  googleplus:
  instagram:
  linkedin:
  pinterest:
  rss: 
  stackoverflow:
  tumblr:
  youtube:
footer-text: Copyright (c) 2022 bj514
disqus:
url: https://aprogrammonkey.github.io
permalink: /:title/
paginate_path: /page:num/
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
sass:
  style: :expanded
plugins:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

